### PR TITLE
Change CSSMathNegate and CSSMathInvert to take numberishes

### PR DESCRIPTION
**Pull request by darrnshn**
Issue #498 .

@nainar PTAL

### CODE REVIEW

**Comment by nainar** [comment]
lgtm on my end. @tabatkins

**Comment by tabatkins** [comment]
This needs additional prose saying that the values, on setting, must rectify a numberish value. (The stored value should always be a CSSNumericValue, but you're allowed to set it with a plain JS number; it just turns into a `CSS.number(x)` automatically for you.)

**Comment by darrnshn** [comment]
Hmm, with the resolution of #513, all the attributes of `CSSMathValues` will become readonly. Would it make more sense then to change all the `CSSNumberish` attributes to `CSSNumericValue`, since we can no longer set the value to a raw number?

**Comment by tabatkins** [comment]
Yeah, they're all CSSNumericValue currently, so I'll go ahead and close this.

**Pull request closed without merging**
