### PR TITLE
[worklets] Reworks "Code Idempotency" section.

### LINKED ISSUE #308: [worklets] Make "Code Idempotency" section normative and stronger
https://drafts.css-houdini.org/worklets/#code-idempotency is a non-normative section that starts with:

> Multiple instances of WorkletGlobalScope can be created for each Worklet that they belong to. User agents may choose to do this in order to parallelize work over multiple threads, or to move work between threads as required.

In order to help make that possible, it goes on with content such as:

> authors […] should make their code idempotent.
> 
> User agents may choose to always have at least two WorkletGlobalScopes per Worklet

I think this is not enough. If one major implementation ships for example CSS Layout API _without_ these "may" precautions, it is likely that many websites will rely and worklet methods being executing in a certain order and in the same global scope. This might effectively make parallelization web-incompatible.

I’d like to make this section normative, and have it specify "must" requirements for user-agents. The details can be discussed, but one idea is to use JavaScript [Frozen Realms](https://github.com/FUDCo/proposal-frozen-realms) to make the global scope immutable (or have an immutable prototype so that creating a new global scope with that same prototype is cheap and could be done for every call).

CC @tschneidereit

### LINKED ISSUE #384: [worklets] "Multiple instances of WorkletGlobalScope can be created for each Worklet that they belong to."
This seems almost certainly wrong for audio worklets, in particular if those are going to use shared memory and such.

cc @bfgeek

### PR DESCRIPTION
**Pull request by bfgeek**
Fixes #384.

Fixes #308. (There is a separate issue for adding the 2
    WorkletGlobalScopes requirement for css-paint-api).

### CODE REVIEW

**Comment by bfgeek** [comment]
@annevk This should be fairly trivial.

This section could also just be moved to the downstream specs which require it, and removed this section; but its probably worth having this here just for context for folks reading it.

There is a separate issue for paint to firm update the global scope requirements.

**Comment by annevk** [comment]
This looks good as an initial revision. I'd aim for something more formal down the line though, where a host specification defines a set of flags and based on that you allocate either one or two or more objects.

**Comment by bfgeek** [comment]
Thats good feedback, I think we'll end up with two classes - one which only one global scope, the other type for layout/paint where we need this ideompotency requirement. A flag eventually makes sense.

**Comment by SimonSapin** [comment]
CC @tschneidereit @metajack

**Pull request merged**
