### PR TITLE
[css-properties-values-api] Allow @property in shadow trees

### PR DESCRIPTION
**Pull request by andruud**

### CODE REVIEW

**Comment by andruud** [comment]
@tabatkins: A question in the form of a PR: did you intend to lift this restriction in https://github.com/w3c/css-houdini-drafts/commit/ed18327ec9e7b898257c39db1ceb87a025110812 ?

It seems odd to have good rationale for a certain ShadowDOM behavior (2.8), and then _not_ allow `@property` in shadow trees.

**Comment by tabatkins** [comment]
...yes, I *did* intend to lift the restriction in that other commit. Thanks for the catch. ^_^

**Comment by foolip** [comment]
Looks like https://github.com/web-platform-tests/wpt/blob/master/css/css-properties-values-api/at-property-shadow.html will need to updated to match what the spec says.

**Comment by emilio** [comment]
@andruud @tabatkins @astearns: Was dis discussed in the working group / was there a resolution on this?

It seems weird that we "leak" property definitions from shadow roots into the global scope. But also the ordering of the registrations etc needs to be defined. I don't think right now we have a dependency between the order of stylesheets inside vs. outside a shadow tree.

**Comment by andruud** [comment]
> ordering of the registrations etc needs to be defined

Indeed, I've also wondered about this.

**Comment by astearns** [comment]
@emilio I think this is a relevant resolution (but a bit vague) https://github.com/w3c/csswg-drafts/issues/1995#issuecomment-848941922

**Comment by emilio** [comment]
@astearns there's no mention of `@property` there, nor in https://drafts.csswg.org/css-scoping-1/#shadow-names which was the section that discussion was about?

**Comment by astearns** [comment]
@emilio more discussion of `@property`: https://github.com/w3c/css-houdini-drafts/issues/939

**Pull request merged**
